# Generated by Django 5.0.3 on 2024-09-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pellet_manufacturing', models.CharField(default='Pellet Manufacturing', max_length=55)),
                ('project_name', models.CharField(default='Project', max_length=55)),
                ('operator', models.CharField(default='Operator', max_length=55)),
                ('pellet_manufacturing1', models.CharField(default='Pellet Manufacturing', max_length=55)),
                ('operator1', models.CharField(default='Anuradha,Pranay', max_length=55)),
                ('operator2', models.CharField(default='A.Srinivas,Laxman', max_length=55)),
                ('operator3', models.CharField(default='Naidu,Ramu', max_length=55)),
                ('operator1p', models.CharField(default='Electrolyte', max_length=55)),
                ('operator2p', models.CharField(default='Cathode', max_length=55)),
                ('operator3p', models.CharField(default='Heat pellet', max_length=55)),
            ],
        ),
    ]
