# Generated by Django 5.0.3 on 2024-09-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0002_process_delete_dailyproduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='date',
        ),
        migrations.RemoveField(
            model_name='process',
            name='process_name',
        ),
        migrations.RemoveField(
            model_name='process',
            name='project_name',
        ),
        migrations.AddField(
            model_name='process',
            name='main_process',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='sub_process',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
