# Generated by Django 5.0.3 on 2024-09-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0003_remove_process_date_remove_process_process_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
