# Generated by Django 5.0.3 on 2024-09-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0004_alter_process_end_time_alter_process_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='end_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='start_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
