# Generated by Django 5.0.3 on 2024-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0012_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='end_info',
        ),
        migrations.RemoveField(
            model_name='process',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start_info',
        ),
        migrations.RemoveField(
            model_name='process',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='interval',
            name='end_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='interval',
            name='start_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='main_process',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='sub_process',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
