# Generated by Django 5.0.3 on 2024-09-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0018_interval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interval',
        ),
    ]
