# Generated by Django 5.0.3 on 2024-09-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0024_remove_process_end_info_remove_process_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinterval',
            name='end_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='processinterval',
            name='start_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
