# Generated by Django 5.0.3 on 2024-09-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0026_process_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinterval',
            name='startend_time',
            field=models.TimeField(null=True),
        ),
    ]
