# Generated by Django 5.0.3 on 2024-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0027_processinterval_startend_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinterval',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
