# Generated by Django 5.0.3 on 2024-09-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0028_processinterval_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinterval',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='process',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
