# Generated by Django 5.0.3 on 2024-10-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0029_remove_processinterval_additional_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_process', models.CharField(max_length=100, null=True)),
                ('sub_process', models.CharField(max_length=100, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInterval1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('startend_time', models.TimeField(null=True)),
                ('start_info', models.CharField(blank=True, max_length=100)),
                ('end_info', models.CharField(blank=True, max_length=100)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='timeintervals.process1')),
            ],
        ),
    ]
