# Generated by Django 5.0.3 on 2024-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0030_process1_processinterval1'),
    ]

    operations = [
        migrations.AddField(
            model_name='process1',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
