# Generated by Django 5.0.3 on 2024-10-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0031_process1_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process1',
            name='name',
        ),
    ]
