# Generated by Django 5.0.3 on 2024-10-09 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0033_processinterval2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinterval2',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='processinterval2',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals_list', to='timeintervals.process'),
        ),
        migrations.AlterField(
            model_name='processinterval2',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
