# Generated by Django 5.0.3 on 2024-10-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0034_alter_processinterval2_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessInterval2',
        ),
    ]
