# Generated by Django 5.0.3 on 2024-10-09 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0035_delete_processinterval2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInterval2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('startend_time', models.TimeField(null=True)),
                ('start_info', models.CharField(blank=True, max_length=100)),
                ('end_info', models.CharField(blank=True, max_length=100)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals2', to='timeintervals.process')),
            ],
        ),
    ]
