# Generated by Django 5.0.3 on 2024-10-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0036_processinterval2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessInterval2',
        ),
    ]
