# Generated by Django 5.0.3 on 2024-10-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0037_delete_processinterval2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinterval1',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals1', to='timeintervals.process'),
        ),
        migrations.DeleteModel(
            name='Process1',
        ),
    ]
