# Generated by Django 5.0.3 on 2024-10-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeintervals', '0038_alter_processinterval1_process_delete_process1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='additional_info',
            new_name='add_info',
        ),
    ]
