from django.db import models

class DailyProduction(models.Model):
    date = models.DateField(auto_now_add=True)  # Automatically set the field to now when the object is created
    pellet_manufacturing = models.CharField(max_length=55,  default='Pellet Manufacturing')
    battery_assembly = models.CharField(max_length=55, default='Battery Assembly')
    project_name = models.CharField(max_length=55,  default='Project') 
    operator = models.CharField(max_length=55,  default='Operator')
    pellet_manufacturing1 = models.CharField(max_length=55,  default='Pellet Manufacturing')
    drying_of_pellets = models.CharField(max_length=55,  default='Drying of pellets')
    moisture_content_test = models.CharField(max_length=55,  default='Moisture Content test')
    storage = models.CharField(max_length=55,  default='Storage')
    mixing_of_anode_powder = models.CharField(max_length=55, default='Mixing of Anode Powder')
    pellet_manufacturing_anode = models.CharField(max_length=55, default='Pellet Manufacturing Anode')
    transfer_of_electrodes_and_components = models.CharField(max_length=55, default='Transfer of electrodes and components')
    cell_assembly = models.CharField(max_length=55, default='Cell Assembly')
    stack_assembly = models.CharField(max_length=55, default='Stack Assembly')
    stack_insulation_wrapping = models.CharField(max_length=55, default='Stack insulation wrapping')
    spot_welding_of_terminals = models.CharField(max_length=55, default='Spot welding of terminals')
    stack_drying = models.CharField(max_length=55, default='Stack Drying')
    battery_welding = models.CharField(max_length=55, default='Battery welding')
    leak_check_for_batteries = models.CharField(max_length=55, default='Leak check for batteries')
    static_parameters_inspection = models.CharField(max_length=55, default='Static parameters inspection')
    handover_to_qc = models.CharField(max_length=55, default='Handover to QC')
    operator1 = models.CharField(max_length=55, default='Anuradha,Pranay')
    operator2 = models.CharField(max_length=55, default='A.Srinivas,Laxman')
    operator3 = models.CharField(max_length=55, default='Naidu,Ramu')
    operator4 = models.CharField(max_length=55, default='Pranay')
    operator5 = models.CharField(max_length=55, default='Laxman')
    operator6 = models.CharField(max_length=55, default='Ramu')
    operator7 = models.CharField(max_length=55, default='Ramu')
    operator8 = models.CharField(max_length=55, default='Naidu')
    operator9 = models.CharField(max_length=55, default='Naidu,Ramu')
    operator10 = models.CharField(max_length=55, default='Laxmi kumari')
    operator11 = models.CharField(max_length=55, default='Krishnaji')
    operator12 = models.CharField(max_length=55, default='Anji')
    operator1p = models.CharField(max_length=55, default='Electrolyte')
    operator2p = models.CharField(max_length=55, default='Cathode')
    operator3p = models.CharField(max_length=55, default='Heat pellet')
    operator4p = models.CharField(max_length=55, default='Electrolyte')
    operator5p = models.CharField(max_length=55, default='Cathode')
    operator6p = models.CharField(max_length=55, default='Heat pellet')
    operator7p = models.CharField(max_length=55, default='Electrolyte')
    operator8p = models.CharField(max_length=55, default='Cathode')
    
    def __str__(self):
        return f"{self.date} Production"
