# Generated by Django 5.0.3 on 2024-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('pellet_manufacturing', models.CharField(default='Pellet Manufacturing', max_length=55)),
                ('battery_assembly', models.CharField(default='Battery Assembly', max_length=55)),
                ('project_name', models.CharField(default='Project', max_length=55)),
                ('operator', models.CharField(default='Pellet Manufacturing', max_length=55)),
                ('pellet_manufacturing1', models.CharField(default='Pellet Manufacturing', max_length=55)),
                ('drying_of_pellets', models.CharField(default='Drying of pellets', max_length=55)),
                ('moisture_content_test', models.CharField(default='Moisture Content test', max_length=55)),
                ('storage', models.CharField(default='Storage', max_length=55)),
                ('mixing_of_anode_powder', models.CharField(default='Mixing of Anode Powder', max_length=55)),
                ('pellet_manufacturing_anode', models.CharField(default='Pellet Manufacturing Anode', max_length=55)),
                ('transfer_of_electrodes_and_components', models.CharField(default='Transfer of electrodes and components', max_length=55)),
                ('cell_assembly', models.CharField(default='Cell Assembly', max_length=55)),
                ('stack_assembly', models.CharField(default='Stack Assembly', max_length=55)),
                ('stack_insulation_wrapping', models.CharField(default='Stack insulation wrapping', max_length=55)),
                ('spot_welding_of_terminals', models.CharField(default='Spot welding of terminals', max_length=55)),
                ('stack_drying', models.CharField(default='Stack Drying', max_length=55)),
                ('battery_welding', models.CharField(default='Battery welding', max_length=55)),
                ('leak_check_for_batteries', models.CharField(default='Leak check for batteries', max_length=55)),
                ('static_parameters_inspection', models.CharField(default='Static parameters inspection', max_length=55)),
                ('handover_to_qc', models.CharField(default='Handover to QC', max_length=55)),
                ('operator1', models.CharField(default='Anuradha,Pranay', max_length=55)),
                ('operator2', models.CharField(default='A.Srinivas,Laxman', max_length=55)),
                ('operator3', models.CharField(default='Naidu,Ramu', max_length=55)),
                ('operator4', models.CharField(default='Pranay', max_length=55)),
                ('operator5', models.CharField(default='Laxman', max_length=55)),
                ('operator6', models.CharField(default='Ramu', max_length=55)),
                ('operator7', models.CharField(default='Ramu', max_length=55)),
                ('operator8', models.CharField(default='Naidu', max_length=55)),
                ('operator9', models.CharField(default='Naidu,Ramu', max_length=55)),
                ('operator10', models.CharField(default='Laxmi kumari', max_length=55)),
                ('operator11', models.CharField(default='Krishnaji', max_length=55)),
                ('operator12', models.CharField(default='Anji', max_length=55)),
                ('operator1p', models.CharField(default='Electrolyte', max_length=55)),
                ('operator2p', models.CharField(default='Cathode', max_length=55)),
                ('operator3p', models.CharField(default='Heat pellet', max_length=55)),
                ('operator4p', models.CharField(default='Electrolyte', max_length=55)),
                ('operator5p', models.CharField(default='Cathode', max_length=55)),
                ('operator6p', models.CharField(default='Heat pellet', max_length=55)),
                ('operator7p', models.CharField(default='Electrolyte', max_length=55)),
                ('operator8p', models.CharField(default='Cathode', max_length=55)),
            ],
        ),
    ]
