# Generated by Django 5.0.3 on 2024-09-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='timer_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='timer_started',
            field=models.BooleanField(default=False),
        ),
    ]
