# Generated by Django 5.0.3 on 2024-09-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_dailyproduction_end_time_dailyproduction_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyproduction',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='timer_completed',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='timer_started',
        ),
    ]
