# Generated by Django 5.0.3 on 2024-09-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_remove_dailyproduction_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('daily_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_intervals', to='display.dailyproduction')),
            ],
        ),
    ]
