# Generated by Django 5.0.3 on 2024-09-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_timeinterval'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeInterval',
        ),
    ]
