# Generated by Django 5.0.3 on 2024-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_delete_timeinterval'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='time_intervals',
            field=models.JSONField(default=dict),
        ),
    ]
