# Generated by Django 5.0.3 on 2024-09-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_dailyproduction_time_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='time_intervals',
            field=models.TextField(default='{}'),
        ),
    ]
