# Generated by Django 5.0.3 on 2024-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_remove_dailyproduction_time_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_1',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_10',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_11',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_12',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_13',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_14',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_15',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_16',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_17',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_18',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_19',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_2',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_20',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_21',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_22',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_3',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_4',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_5',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_6',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_7',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_8',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_1_cell_9',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_1',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_10',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_11',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_12',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_13',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_14',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_15',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_16',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_17',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_18',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_19',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_2',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_20',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_21',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_22',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_3',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_4',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_5',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_6',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_7',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_8',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='interval_2_cell_9',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='time_interval_1',
            field=models.CharField(default='8:30 to 8:40', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='time_interval_2',
            field=models.CharField(default='8:40 to 8:50', max_length=20),
        ),
    ]
