# Generated by Django 5.0.3 on 2024-09-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_remove_dailyproduction_interval_1_cell_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproduction',
            name='operator',
            field=models.CharField(default='Operator', max_length=55),
        ),
    ]
