# Generated by Django 5.0.3 on 2024-10-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Process',
            new_name='Process1',
        ),
        migrations.RenameModel(
            old_name='ProcessInterval',
            new_name='ProcessInterval1',
        ),
    ]
