# Generated by Django 5.0.3 on 2024-10-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_process'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Process',
        ),
    ]
